apiVersion: v1
kind: Namespace
metadata:
  name: mnm-car-recommend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnm-car-inventory
  namespace: mnm-car-recommend
  labels:
    app: mnm-car-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnm-car-inventory
  template:
    metadata:
      labels:
        app: mnm-car-inventory
    spec:
      containers:
      - name: mnm-car-inventory
        image: mnm-car-inventory:0.1
        ports:
        - containerPort: 8082
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mnm-car-inventory
  namespace: mnm-car-recommend
spec:
  type: ClusterIP
  selector:
    app: mnm-car-inventory
  ports:
    - name: mnm-car-inventory-port
      port: 8082
      protocol: TCP

