apiVersion: v1
kind: Service
metadata:
  name: mnm-car-inventory-service
  namespace: mnm-car-recommend
spec:
  type: NodePort
  selector:
    app: mnm-car-inventory-deployment
  ports:
  - port: 8082
    targetPort: 8082
    nodePort: 30082
